version: "3.9"
services:
  webapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true