version: "3.9"
services:
  sbm-modernization-frontend:
    container_name: sbm-modernization-frontend
    domainname: "mattburnsidesbmcourse"
    depends_on: [sbm-modernization-frontend]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mattburnsidespringbootmodernizationcourseregistry.azurecr.io/sbm-modernization-frontend
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SBM_API_ROOT_URL=http://mattburnsidesbmcourse.eastus.azurecontainer.io:8080/
  sbm-modernization-backend:
    container_name: sbm-modernization-backend
    domainname: "mattburnsidesbmcourse"
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mattburnsidespringbootmodernizationcourseregistry.azurecr.io/sbm-modernization-backend
    ports:
      - "8080:8080"